### ISSUE TITLE
JS Date object not transformed to ISO string

### ISSUE THREAD

**Issue by servercimen** [segmentio/analytics-react-native#835]
An event property of type "Date time" is translated to JS with type "Date" by typewriter. However, when this is send to segment backend it's showing up as the following on segment debugger instead of ISO string. 

Manually sending an ISO string representation of the date object causes type errors as expected.

Please note that we have a similar setup for our website and sending a Date object works find with segment analytics-react.

```
"date": {
      "type": "UNIX_timestamp",
      "value": 1684540800000
    },
```

- `analytics-react-native` version: 2.14.0
-  typewriter version: 8.0.10
- React Native version: 0.70.6
- Happens on iOS and Android
- typewriter client config:
```
client:
  #You can find more documentation on configuring this client in the Segment docs
  #See: https://segment.com/docs/protocols/typewriter
  language: typescript
  sdk: analytics-react-native
  languageOptions: {}
```

**Steps to reproduce**
- Define an event with date time property. JSON schema looks like this
```
        "date": {
          "description": "date the user entered",
          "format": "date-time",
          "id": "/properties/properties/properties/date",
          "type": [
            "string",
            "null"
          ]
        },
```
- Run typewriter to generate code
- The "date" property has type Date
- Track the property by passing a Date object such as `new Date("2023-05-19")`

**Expected behavior**
The date is send to segment backend as an ISO string like the following:
"date": "2023-06-02T07:00:00.000Z"

**Actual behavior**
It's recorded as an object with two keys as demonstrated below.
```
"date": {
      "type": "UNIX_timestamp",
      "value": 1685689200000
    },
```
